import { useState } from 'react'
import { Empty, ErrorState, Loading, Panel, SeverityTag } from '../components/Primitives'
import { api } from '../lib/api'
import { useData } from '../lib/useData'
import { when } from '../lib/format'

const TYPES = [
  { key: 'daily', label: 'Daily site report' },
  { key: 'executive', label: 'Executive summary' },
  { key: 'audit', label: 'Audit documentation' },
  { key: 'project-health', label: 'Project health' },
]

export default function Reports({ projectId, refreshKey }) {
  const reports = useData(() => api.reports(projectId), [projectId, refreshKey])
  const alerts = useData(() => api.alerts(projectId), [projectId, refreshKey])
  const [selected, setSelected] = useState(null)
  const [busy, setBusy] = useState(null)

  if (reports.error) return <ErrorState error={reports.error} onRetry={reports.reload} />

  const generate = async (type) => {
    setBusy(type)
    try {
      const report = await api.generateReport(projectId, type)
      setSelected(report)
      reports.reload()
    } finally {
      setBusy(null)
    }
  }

  const open = selected ?? reports.data?.[0]

  return (
    <div className="space-y-5">
      <Panel title="Generate documentation" note="The Reporting Agent aggregates every agent finding into an audit-ready document">
        <div className="flex flex-wrap gap-2">
          {TYPES.map((type) => (
            <button
              key={type.key}
              onClick={() => generate(type.key)}
              disabled={busy === type.key}
              className="border border-site-500 px-3 py-2 font-display text-sm text-concrete hover:border-hivis hover:text-hivis disabled:opacity-50"
            >
              {busy === type.key ? 'Writing…' : type.label}
            </button>
          ))}
        </div>
      </Panel>

      <div className="grid gap-5 lg:grid-cols-3">
        <Panel title="Report archive" note={`${reports.data?.length ?? 0} documents on file`}>
          {reports.loading && !reports.data ? (
            <Loading label="Loading reports" />
          ) : reports.data?.length ? (
            <ul className="max-h-[420px] space-y-1 overflow-auto text-sm">
              {reports.data.map((report) => (
                <li key={report.report_id}>
                  <button
                    onClick={() => setSelected(report)}
                    className={`w-full border-l-2 px-3 py-2 text-left ${
                      open?.report_id === report.report_id ? 'border-hivis bg-site-600 text-concrete' : 'border-transparent text-steel hover:text-concrete'
                    }`}
                  >
                    <span className="block capitalize">{report.report_type.replace('-', ' ')}</span>
                    <span className="block text-xs text-steel">{when(report.generated_at)}</span>
                  </button>
                </li>
              ))}
            </ul>
          ) : (
            <Empty>No reports yet. Generate one above.</Empty>
          )}
        </Panel>

        <Panel className="lg:col-span-2" title={open?.title ?? 'Report'} note={open ? `Generated by ${open.generated_by.replace(/_/g, ' ')}` : ''}>
          {open ? (
            <pre className="max-h-[420px] overflow-auto whitespace-pre-wrap font-sans text-sm leading-relaxed text-concrete">
              {open.body}
            </pre>
          ) : (
            <Empty>Select a report to read it.</Empty>
          )}
        </Panel>
      </div>

      <Panel title="Alert log" note="Every notification raised by the agent network">
        {alerts.data?.length ? (
          <div className="max-h-[320px] overflow-auto">
            <table className="w-full min-w-[560px] text-sm">
              <thead className="sticky top-0 bg-site-700 text-left text-xs text-steel">
                <tr className="border-b border-site-500/60">
                  <th className="pb-2 font-medium">Severity</th>
                  <th className="pb-2 font-medium">Message</th>
                  <th className="pb-2 font-medium">Channels</th>
                  <th className="pb-2 font-medium">Raised</th>
                  <th className="pb-2 font-medium">State</th>
                </tr>
              </thead>
              <tbody>
                {alerts.data.map((alert) => (
                  <tr key={alert.alert_id} className="border-b border-site-500/30">
                    <td className="py-2 pr-3"><SeverityTag severity={alert.severity} /></td>
                    <td className="py-2 pr-3 text-concrete">{alert.message}</td>
                    <td className="py-2 pr-3 text-xs text-steel">{alert.channel}</td>
                    <td className="py-2 pr-3 text-xs text-steel">{when(alert.created_at)}</td>
                    <td className={`py-2 text-xs ${alert.acknowledged ? 'text-clear' : 'text-caution'}`}>
                      {alert.acknowledged ? 'acknowledged' : 'open'}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <Empty>No alerts raised yet.</Empty>
        )}
      </Panel>
    </div>
  )
}
